import {expect, it} from "vitest";
import {DeckDownloader} from "../tools/DeckDownloader.ts";

it('should return deck', async () => {
    const input = `1x Abrade (vow) 139 [Removal]
1x Ancient Stone Idol (mkc) 222 [Creature]
1x Anger (afc) 113 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Arcbound Ravager (mma) 198 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Atsushi, the Blazing Sky (pneo) 134p [Creature]
1x Ball Lightning (mb2) 130 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Battlemage's Bracers (c21) 48 [Copy]
1x Big Score (otc) 155 [Sideboard,Maybeboard{noDeck}{noPrice},Rummage,Ramp]
1x Blasphemous Act (c21) 159 [Removal] ^Don't Have,#f47373^
1x Blast-Furnace Hellkite (brc) 12 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Bosh, Iron Golem (c21) 237 [Maybeboard{noDeck}{noPrice}]
1x Bottle-Cap Blast (pip) 55 [Maybeboard{noDeck}{noPrice}]
1x Brass's Tunnel-Grinder // Tecutlan, the Searing Rift (lci) 135 [Artifact]
1x Breaker of Armies (plst) BFZ-3 [Maybeboard{noDeck}{noPrice}]
1x Cathartic Pyre (mid) 133 [Rummage]
1x Cathartic Reunion (iko) 110 [Rummage]
1x Change of Fortune (vow) 150 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Chaos Warp (otc) 160 [Removal] ^Don't Have,#f47373^
1x Cityscape Leveler (bro) 233 [Maybeboard{noDeck}{noPrice}]
1x Clone Shell (2xm) 241 [Draw]
1x Collector's Vault (woe) 244 [Sideboard,Maybeboard{noDeck}{noPrice}]
1x Combustible Gearhulk (scd) 128 [Draw]
1x Command Beacon (otc) 279 [Land]
1x Connecting the Dots (mkm) 118 [Maybeboard{noDeck}{noPrice}]
1x Containment Construct (neo) 243 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Crime Novelist (mkm) 121 [Maybeboard{noDeck}{noPrice}]
1x Currency Converter (ncc) 81 [Tokens]
1x Cursed Mirror (otc) 161 [Ramp]
1x Cybermen Squadron (who) 176 [Creature]
1x Daretti, Rocketeer Engineer (dft) 358 [Creature]
1x Daretti, Scrap Savant (oc14) 33 *F* [Recursion]
1x Deal Broker (cns) 61 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Demand Answers (mkm) 122 [Rummage]
1x Determined Iteration (ncc) 45 [Tokens]
1x Dowsing Device // Geode Grotto (lci) 146 [Maybeboard{noDeck}{noPrice},Sideboard,Artifact]
1x Drakuseth, Maw of Flames (clb) 790 [Sideboard,Maybeboard{noDeck}{noPrice}]
1x Dross Scorpion (mrd) 164 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Dualcaster Mage (c21) 165 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Duplicant (cmm) 946 [Maybeboard{noDeck}{noPrice}]
1x Embercleave (spg) 77 [Pump]
1x Enterprising Scallywag (lci) 148 [Creature]
1x Eriette's Tempting Apple (woe) 245 [Maybeboard{noDeck}{noPrice}]
1x Etali, Primal Storm (afc) 126 [Creature]
1x Exuberant Fuseling (one) 129 [Creature]
1x Fable of the Mirror-Breaker // Reflection of Kiki-Jiki (neo) 141 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Faithless Looting (otc) 165 [Loot]
1x Feldon of the Third Path (c19) 141 [Commander{top}]
1x Feldon's Cane (chr) 97 [Recursion]
1x Ferocification (otj) 123 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Fiery Emancipation (m21) 143 [Maybeboard{noDeck}{noPrice}] ^Getting,#2ccce4^
1x Firbolg Flutist (clb) 174 [Theft]
1x Fire Diamond (voc) 164 [Maybeboard{noDeck}{noPrice},Sideboard,Ramp]
1x Flayer of the Hatebound (c19) 144 [Removal] ^Getting,#2ccce4^
1x Fledgling Dragon (mh3) 280 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Fomori Vault (big) 94 [Land]
1x Forgotten Cave (onc) 153 [Maybeboard{noDeck}{noPrice},Sideboard,Land]
1x Foundry Inspector (cmm) 385 [Maybeboard{noDeck}{noPrice}]
1x Geier Reach Sanitarium (afc) 241 [Land]
1x Gilded Lotus (cmm) 387 [Maybeboard{noDeck}{noPrice},Sideboard,Ramp]
1x Gleeful Demolition (one) 134 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Glint-Horn Buccaneer (j22) 539 [Maybeboard{noDeck}{noPrice}]
1x Goblin Engineer (mh1) 128 [Tutor] ^Don't Have,#f47373^
1x Goblin Welder (ddu) 35 *F* [Recursion]
1x Golem Artisan (j22) 770 [Maybeboard{noDeck}{noPrice}]
1x Guff Rewrites History (cmm) 737 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Hanweir Battlements (emn) 204 [Land] ^Don't Have,#f47373^
1x Hellkite Tyrant (rvr) 111 [Removal]
1x Highway Robbery (otj) 129 [Rummage]
1x Hoarding Dragon (cmm) 233 [Maybeboard{noDeck}{noPrice},Sideboard,Tutor]
1x Illusionist's Bracers (rvr) 392 [Maybeboard{noDeck}{noPrice},Sideboard,Copy]
1x Industrial Advancement (ncc) 47 [Maybeboard{noDeck}{noPrice}]
1x Infantry Shield (tdc) 35 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Inferno Titan (cmm) 235 [Maybeboard{noDeck}{noPrice}]
1x Ingot Chewer (plst) CM2-110 [Maybeboard{noDeck}{noPrice}]
1x Invasion of Kaldheim // Pyre of the World Tree (mom) 145 [Sideboard,Maybeboard{noDeck}{noPrice}]
1x Jaxis, the Troublemaker (snc) 461 *F* [Copy]
1x Junk Diver (cm2) 195 [Maybeboard{noDeck}{noPrice}]
1x Liquimetal Torque (mh2) 428 [Ramp]
1x Magewright's Stone (rvr) 462 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Magmakin Artillerist (dft) 137 [Burn]
1x Magus of the Wheel (ncc) 271 [Wheel]
1x Mana Geyser (scd) 151 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Mask of Memory (onc) 136 [Maybeboard{noDeck}{noPrice},Sideboard,Loot]
1x Merchant of the Vale // Haggle (eld) 131 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Metalwork Colossus (cmm) 960 [Maybeboard{noDeck}{noPrice}]
1x Meteor Golem (cmr) 325 [Removal]
1x Mind Stone (40k) 244 [Sideboard,Maybeboard{noDeck}{noPrice},Ramp]
1x Mirage Mirror (cmm) 962 [Maybeboard{noDeck}{noPrice}]
1x Mirrorpool (cmm) 1010 [Land]
1x Mishra's Command (bro) 141 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Mishra, Excavation Prodigy (bro) 140 [Rummage,Ramp]
1x Molten Duplication (big) 79 [Copy]
1x Molten Primordial (gtc) 101 [Maybeboard{noDeck}{noPrice},Sideboard,Theft]
25x Mountain (mkm) 283 [Land]
1x Myr Battlesphere (brc) 151 [Tokens]
1x Myr Retriever (plst) CM2-203 [Maybeboard{noDeck}{noPrice}]
1x Myriad Landscape (ncc) 416 [Land]
1x Neheb, Dreadhorde Champion (dmc) 125 [Creature]
1x Null Brooch (exo) 136 [Maybeboard{noDeck}{noPrice}]
1x Oliphaunt (ltr) 139 [Maybeboard{noDeck}{noPrice}]
1x Orthion, Hero of Lavabrink (mom) 334 [Maybeboard{noDeck}{noPrice}]
1x Palladium Myr (m21) 234 [Ramp]
1x Panharmonicon (pip) 237 [Maybeboard{noDeck}{noPrice},Sideboard,Blink]
1x Patriar's Seal (clb) 332 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Phyrexian Triniform (moc) 370 [Tokens]
1x Pirate's Pillage (2x2) 120 [Maybeboard{noDeck}{noPrice},Sideboard,Rummage]
1x Professional Face-Breaker (snc) 116 [Ramp]
1x Purphoros, Bronze-Blooded (thb) 150 [Copy] ^Don't Have,#f47373^
1x Pyroblast (ice) 213 [Sideboard,Maybeboard{noDeck}{noPrice}]
1x Quicksmith Genius (c21) 178 [Maybeboard{noDeck}{noPrice}]
1x Rampaging War Mammoth (ltc) 34 [Maybeboard{noDeck}{noPrice}]
1x Reckless Fireweaver (j22) 587 [Maybeboard{noDeck}{noPrice}]
1x Reckless Handling (mat) 19 [Sideboard,Maybeboard{noDeck}{noPrice}]
1x Red Elemental Blast (4ed) 218 [Sideboard,Maybeboard{noDeck}{noPrice}]
1x Rimescale Dragon (csp) 95 [Maybeboard{noDeck}{noPrice}]
1x Rogue's Passage (lcc) 349 [Maybeboard{noDeck}{noPrice},Sideboard,Land]
1x Rousing Refrain (otc) 178 [Ramp]
1x Ruin Grinder (plst) C21-57 [Wheel]
1x Rummaging Goblin (j22) 591 [Rummage]
1x Sandstone Oracle (cmr) 336 [Maybeboard{noDeck}{noPrice},Sideboard,Creature]
1x Scrap Mastery (c14) 38 [Maybeboard{noDeck}{noPrice},Sideboard,Recursion]
1x Scrap Trawler (brr) 112 *F* [Recursion]
1x Scrap Welder (neo) 159 [Recursion]
1x Sculpting Steel (brr) 50 [Copy]
1x Scuttling Doom Engine (c18) 219 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Seize the Spoils (gn3) 86 [Rummage]
1x Shivan Dragon (sld) 1709 [Sideboard,Finisher]
1x Siege Smash (mh3) 136 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Skullclamp (moc) 379 [Maybeboard{noDeck}{noPrice},Sideboard,Draw]
1x Skyclave Relic (pznr) 252p [Ramp]
1x Slobad, Goblin Tinkerer (brc) 118 [Maybeboard{noDeck}{noPrice}]
1x Slobad, Iron Goblin (one) 149 [Maybeboard{noDeck}{noPrice}]
1x Smuggler's Copter (nec) 160 [Maybeboard{noDeck}{noPrice}]
1x Sneak Attack (dmr) 139 [Maybeboard{noDeck}{noPrice}]
1x Sol Ring (otc) 267 [Ramp]
1x Solemn Simulacrum (m3c) 306 [Ramp] ^Don't Have,#f47373^
1x Spawn of Thraxes (jou) 112 [Maybeboard{noDeck}{noPrice},Creature]
1x Spitebellows (c13) 120 [Sideboard,Removal]
1x Steel Hellkite (c21) 266 [Creature]
1x Su-Chi Cave Guard (bro) 249 [Maybeboard{noDeck}{noPrice},Creature]
1x Sunspine Lynx (blb) 155 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Swiftfoot Boots (otc) 268 [Protection]
1x Temple of the False God (otc) 334 [Land]
1x Terror of the Peaks (otj) 337 [Removal]
1x Thousand-Year Elixir (lrw) 263 [Untap] ^Don't Have,#f47373^
1x Threefold Thunderhulk (lci) 390 [Tokens]
1x Thrill of Possibility (m21) 165 [Rummage]
1x Tibalt's Trickery (khm) 153 [Sideboard,Maybeboard{noDeck}{noPrice}]
1x Tomakul Scrapsmith (bro) 153 [Maybeboard{noDeck}{noPrice}]
1x Tormenting Voice (znr) 172 [Rummage]
1x Trading Post (brc) 169 [Artifact]
1x Trash for Treasure (2xm) 148 [Recursion]
1x Treasure Map // Treasure Cove (lci) 267 [Maybeboard{noDeck}{noPrice}]
1x Treasure Vault (pip) 314 [Land]
1x Triplicate Titan (c21) 79 [Sideboard,Maybeboard{noDeck}{noPrice}]
1x Twins of Discord (m3c) 37 [Maybeboard{noDeck}{noPrice},Sideboard,Creature]
1x Tyrant of Discord (avr) 162 [Maybeboard{noDeck}{noPrice},Sideboard]
1x Tyrant's Familiar (c17) 143 [Removal]
1x Unexpected Windfall (pip) 193 [Maybeboard{noDeck}{noPrice},Sideboard,Rummage,Ramp]
1x Urza's Mine (chr) 114a [Land]
1x Urza's Power Plant (chr) 115c [Land]
1x Urza's Tower (chr) 116b [Land]
1x Utvara Hellkite (rvr) 129 [Maybeboard{noDeck}{noPrice}]
1x Volatile Fault (lci) 286 [Maybeboard{noDeck}{noPrice}]
1x Warstorm Surge (blc) 117 [Sideboard,Maybeboard{noDeck}{noPrice},Removal]
1x Wild Guess (m13) 157 [Maybeboard{noDeck}{noPrice},Sideboard,Rummage]
1x Workshop Assistant (cmr) 348 [Maybeboard{noDeck}{noPrice}]
1x Wurmcoil Engine (cm2) 231 [Sideboard,Maybeboard{noDeck}{noPrice},Tokens] ^Top,#f504ad^`;

    const deck = await DeckDownloader.getFromString(input);
    console.log(deck);
});