import * as fs from "node:fs";
import {DeckDownloader} from "../src/tools/DeckDownloader.ts";

const input = `1x "Lifetime" Pass Holder (unf) 79 [Recursion]
1x Agility Bobblehead (pip) 126 [Ramp]
1x Altar of Dementia (brr) 3 [Sac Outlet]
1x Army of the Damned (isd) 87 [Tokens]
1x Ashnod's Altar (ema) 218 [Ramp]
1x Ayara, First of Locthwain (peld) 75p [Draw]
1x Black Hole (unf) 67 [Removal]
1x Blood Artist (inr) 97 [Drain]
1x Bojuka Bog (clb) 882 [Land]
1x Bontu's Monument (akh) 225 [Ramp]
1x Cabal Coffers (hop) 132 [Land]
1x Cabal Stronghold (dom) 238 [Land]
1x Cemetery Reaper (m10) 87 [Anthem]
1x Champion of the Perished (mid) 385 *F* [Tokens]
1x Charisma Bobblehead (pip) 130 [Ramp]
1x Clown Car (unf) 186 [Tokens]
1x Clown Extruder (unf) 204d [Attraction{noDeck}]
1x Concession Stand (unf) 205a [Attraction{noDeck}]
1x Crypt Ghast (c14) 139 [Ramp]
1x Dark Ritual (itp) 19 [Ramp]
1x Deadbeat Attendant (unf) 69 [Creature]
1x Death Baron (pm19) 90p [Anthem]
1x Defile (mh1) 86 [Removal]
1x Diregraf Colossus (psoi) 107s *F* [Tokens]
1x Drop Tower (unf) 209a [Attraction{noDeck}]
1x Endless Ranks of the Dead (isd) 99 [Tokens]
1x Endurance Bobblehead (pip) 132 [Ramp]
1x Exquisite Blood (lcc) 195 [Lifegain]
1x Foam Weapons Kiosk (unf) 211a [Attraction{noDeck}]
1x Fortune Teller (unf) 212a [Attraction{noDeck}]
1x Grave Pact (9ed) 135 [Removal]
1x Gray Merchant of Asphodel (thb) 99 [Drain]
1x Gríma Wormtongue (ltr) 88 [Sac Outlet]
1x Hall of Mirrors (unf) 216a [Attraction{noDeck}]
1x Headless Rider (dbl) 385 [Tokens]
1x Information Booth (unf) 218a [Attraction{noDeck}]
1x Intelligence Bobblehead (pip) 134 [Ramp]
1x Jet Medallion (c14) 243 [Ramp]
1x Kalakscion, Hunger Tyrant (dft) 93 [Finisher]
1x Kiddie Coaster (unf) 219a [Attraction{noDeck}]
1x Line Cutter (unf) 80 [Creature]
1x Lord of the Accursed (drc) 95 [Anthem]
1x Luck Bobblehead (pip) 135 [Ramp]
1x Maga, Traitor to Mortals (sok) 81 [Burn]
1x Marionette Apprentice (mh3) 100 [Drain]
1x Marionette Master (kld) 90 [Drain]
1x Mirkwood Bats (ltr) 95 [Drain]
1x Nim Deathmantle (som) 188 [Recursion]
1x Perception Bobblehead (pip) 139 [Ramp]
1x Pick-a-Beeble (unf) 223a [Attraction{noDeck}]
1x Plague of Vermin (shm) 73 [Tokens]
1x Putrid Goblin (mh1) 101 [Counters]
1x Quick Fixer (unf) 85 [Creature]
1x Reliquary Tower (c16) 316 [Land]
1x Sanguine Bond (ltc) 208 [Drain]
1x Skullclamp (cmd) 260 [Draw]
1x Sol Ring (c16) 272 [Ramp]
1x Soul Swindler (unf) 93 [Creature]
1x Step Right Up (unf) 94 [Sorcery]
1x Strength Bobblehead (pip) 143 [Ramp]
39x Swamp (dft) 285 [Land]
1x Swinging Ship (unf) 231a [Attraction{noDeck}]
1x Thran Vigil (bro) 114 [Counters]
1x Tormod, the Desecrator (cmr) 155 [Tokens]
1x Undead Warchief (scg) 78 *F* [Ramp]
1x Vadmir, New Blood (otj) 113 [Counters]
1x Vengeful Dead (scg) 80 [Drain]
1x Viscera Seer (cmr) 158 [Sac Outlet]
1x Vito, Thorn of the Dusk Rose (m21) 127 [Drain]
1x Vraan, Executioner Thane (one) 114 [Creature]
1x Zombie Apocalypse (mic) 131 [Recursion]
1x Zul Ashur, Lich Lord (fdn) 77 [Commander{top}]`;

const deck = await DeckDownloader.getFromString(input);
console.log(deck);
fs.writeFileSync("test.json", JSON.stringify(deck, null, 2));