export interface ArchidektDeck {
    id: number;
    name: string;
    createdAt: string;
    updatedAt: string;
    deckFormat: number;
    edhBracket: number | null;
    game: any | null;
    description: string;
    viewCount: number;
    featured: string;
    customFeatured: string;
    private: boolean;
    unlisted: boolean;
    theorycrafted: boolean;
    points: number;
    userInput: number;
    owner: {
        id: number;
        username: string;
        avatar: string;
        frame: any | null;
        ckAffiliate: string;
        tcgAffiliate: string;
        referrerEnum: any | null;
    };
    commentRoot: number;
    editors: any | null;
    parentFolder: number;
    bookmarked: boolean;
    categories: {
        id: number;
        name: string;
        isPremier: boolean;
        includedInDeck: boolean;
        includedInPrice: boolean;
    }[];
    deckTags: any[];
    playgroupDeckUrl: string | null;
    cardPackage: any | null;
    cards: ArchidektCard[];
}

export interface ArchidektCard {
    id: number;
    categories: string[];
    companion: boolean;
    flippedDefault: boolean;
    label: string;
    modifier: string;
    quantity: number;
    customCmc: number | null;
    removedCategories: any | null;
    createdAt: string;
    updatedAt: string;
    deletedAt: string | null;
    card: {
        id: number;
        artist: string;
        tcgProductId: number;
        ckFoilId: number;
        ckNormalId: number;
        cmEd: string;
        scgSku: string;
        scgFoilSku: string;
        collectorNumber: string;
        multiverseid: number;
        mtgoFoilId: number;
        mtgoNormalId: number;
        uid: string;
        displayName: string | null;
        edition: {
            editioncode: string;
            editionname: string;
            editiondate: string;
            editiontype: string;
            mtgoCode: string | null;
        };
        flavor: string;
        games: any[];
        options: string[];
        scryfallImageHash: string;
        oracleCard: {
            id: number;
            cmc: number;
            colorIdentity: string[];
            colors: string[];
            edhrecRank: number;
            faces: any[];
            layout: string;
            uid: string;
            legalities: {
                alchemy: string;
                legacy: string;
                oldschool: string;
                modern: string;
                vintage: string;
                oathbreaker: string;
                "1v1": string;
                historicbrawl: string;
                premodern: string;
                historic: string;
                commander: string;
                paupercommander: string;
                gladiator: string;
                explorer: string | null;
                brawl: string;
                penny: string;
                pioneer: string;
                duel: string;
                pauper: string;
                standard: string;
                future: string;
                predh: string;
                timeless: string;
                canlander: string;
            };
            manaCost: string;
            manaProduction: {
                W: number;
                U: number;
                B: number;
                R: number;
                G: number;
                C: number | null;
            };
            name: string;
            power: string;
            salt: number;
            subTypes: string[];
            superTypes: string[];
            keywords: string[];
            text: string;
            tokens: any[];
            toughness: string;
            types: string[];
            loyalty: number | null;
            canlanderPoints: number | null;
            isPDHCommander: boolean;
            defaultCategory: string;
            gameChanger: boolean;
            extraTurns: boolean;
            tutor: boolean;
            massLandDenial: boolean;
            twoCardComboSingelton: boolean;
            twoCardComboIds: any[];
            atomicCombos: any[];
            potentialCombos: any[];
        };
        owned: number;
        prices: {
            ck: number;
            ckfoil: number;
            cm: number;
            cmfoil: number;
            mtgo: number;
            mtgofoil: number;
            tcg: number;
            tcgfoil: number;
            scg: number;
            scgfoil: number;
            mp: number;
            mpfoil: number;
            tcgLand: number;
            tcgLandFoil: number;
        };
        rarity: string;
        globalCategories: any[];
    };
}